### ISSUE TITLE
Could not find enough inliers in imagePoints and worldPoints

### ISSUE THREAD

**Issue by yuan0821** [spoonsso/dannce#126]
Hi. I used the calibration script, but an error occurs in matlab when doing **estimateWorldCameraPose**
**`Could not find enough inliers in imagePoints and worldPoints.`**
here are our parameters for one camera:
![image](https://user-images.githubusercontent.com/50692530/191244117-c4ab8fc4-60c2-4052-86ef-fb1ec12379cf.png)
![image](https://user-images.githubusercontent.com/50692530/191244737-55370910-eca5-4a58-8afa-8cc259e8607d.png)

I think we clicked 4 points in the [xi,yi] = getpts ; but the error still said our imagePoints < 4.

**Comment by spoonsso** [comment]
You are getting that error because it is throwing away some of your points as outliers w/ high reprojection error. This is likely happening because of an issue with the intrinsic calibration. Looking at your intrinsic parameters, they seem irregular -- for instance, the principal point is normally close to the center of the image, whereas yours is off near the corner. This suggests to me that that intrinsics were not fit well.

See #127, perhaps you should try the anipose calibration system.

**Comment by yuan0821** [comment]
Hi! Thank you so much for your reply. I will try to check the intrinsic params and re-calibrate again. 
Btw, when I try to use the script of **dannce/calibration/multi-camera calibration/calibration_extrinsic_Lframe.m**, it seems to work well on the same intrinsic params, I can get the extrinsic matrix and Triangulate them well in Label3D. 
So I just wonder if it may be the reason of dannce/calibration/acquire_calibration_3cam_mouse_clean.m?
