### ISSUE TITLE
Could not find enough inliers in imagePoints and worldPoints

### ISSUE THREAD

**Issue by yuan0821** [spoonsso/dannce#136]
Hi! does anybody meet the weird error when doing extrinsic calibration? I struggled with extrinsic calibration. 
The same picture and the same intrinsic parameter; however, whenever I label the 4 points of coordination, the error comes randomly. So I did intrinsic calibration again to ensure the intrinsics were normal(error <0.15 pixels).

Sometimes it works well, and the result of doing Lablel3D is ok; sometimes, everything is failed. Appreciate any suggestions.

![image](https://user-images.githubusercontent.com/50692530/206358312-03f1cd21-7995-4a1a-87c5-5f59479eca38.png)
here is my intrinsic matrix: (all camera are the same type, but not sure why camera3 have different parameters)
![image](https://user-images.githubusercontent.com/50692530/206360221-141df359-efa6-40a8-9325-36eb432127e0.png)

**Comment by yuan0821** [comment]
Below is the Label3D abnormal result, even though there is no error in the extrinsic calibration.
![image](https://user-images.githubusercontent.com/50692530/206361930-8bb6e345-0101-4aff-b10a-5b8abb11e8a0.png)

**Comment by data-hound** [comment]
Hi @yuan0821 

About the camera3 being different, does it have a different crop factor than the other cameras? Or is the ROI after cropping too far away from the true center of the camera view? Cropping and translation can change intrinsics.

As for the extrinsic calibration failing randomly, that could be due to a variety of reasons. But, keep in mind that under the hood, the [estimateWorldCameraPose](https://www.mathworks.com/help/vision/ref/estimateworldcamerapose.html) uses a [MSAC algorithm](https://www.robots.ox.ac.uk/~vgg/publications/2000/Torr00/torr00.pdf) to determine inliers, which is a stochastic algorithm. So, I would expect the output to vary slightly and maybe with only 4 labels a sufficient overlap may not be feasible. _I would suggest trying to increase the number of labelled points_.
