### ISSUE TITLE
predictions.mat File in CAPTURE_demo Code

### ISSUE THREAD

**Issue by verpeutlab** [spoonsso/dannce#43]
Thank you for responding so quickly! 
I have read through the response you have provided, and I have been using the CAPTURE_demo code. However, I am unable to find a file titled predictions.mat in the DANNCE demo code, which was referenced in the preprocess_dannce.m file from the CAPTURE_demo code. I have successfully cloned the master branch of DANNCE, and I have ran the DANNCE Quickstart Demo. I did see a file titled predictions.mat at the bottom of the  CAPTURE_demo code GitHub page, but I am not sure how to generate this file when running DANNCE.

**Comment by spoonsso** [comment]
`predictions.mat` is generated by `dannce/utils/makeStructuredDataNoMocap.py`. It wraps some useful metadata into the predictions files, including the names of each tracked landmark, the camera parameters, and video paths. The required skeleton file for the demo mouse data can be found at https://github.com/diegoaldarondo/Label3D/blob/master/skeletons/mouse22.mat.

We decided not to format the dannce predictions this way as they stream out of `dannce-predict` because the format is somewhat bespoke for our personal downstream analyses. But if there is enough interest in integrating it, I can work on that. The easiest solution would probably be a bash script that executes `dannce-predict` followed by `makeStructuredDataNoMocap.py`
