### ISSUE TITLE
Which frames are used for dannce-train & dannce-predict?

### ISSUE THREAD

**Issue by kantkantwuqh** [spoonsso/dannce#74]
I have followed the instructions on github, but still meet several questions:

1. Take markerless_mouse_1 as example, there are 6 cameras, each with 6 videos inside, so how can I select the frames from specific videos of specific cameras for training and predicting?

2. After running the code without changing any parameter, I got the file .\dannce\demo\markerless_mouse_1\DANNCE\predict_results\save_data_AVG0.mat'. Inside the file, the value of 'pred' has shape (1000,3,22), then how can I know which 1000 frames are predicted(because I want to merge the prediction with the original frames)?

**Comment by spoonsso** [comment]
1)	The frames that will be sed to train are all inside label3d_dannce.mat (label3d_demo.mat also contains training frames, but they are a small subset of the full set). Take a look at the file in Matlab. The “labelData” variable holds the labels inside the member “data_3d” field. The frame indices associated with these labels are found in the member “data_frame” field. “labelData” has an entry for each camera because the “data_frame” can technically be different for each camera, depending on synchronization. But the “data_3d” field will be identical across cameras.
a.	If you label new frames using Label3D, then the end result will be a new `label3d_dannce.mat` file with contains the labels and the indices of the frames that were labeled. These new labels could then be used for training (dannce will pull in the correct frames based on the indices in “labelData.data_frame”.
b.	For predicting after training is complete (with dannce-predict), the default is to make predictions for every frame contained within the “sync” variable inside label3d_dannce.mat. If you want to be able to predict over an entire movie (as we already have set up for the demo to do), then the “data_frame” variables inside of “sync” must have an entry for each frame. Once your “sync” is specified correctly, you can opt to make predictions over subsets of frames by setting the “start_sample” and “max_num_samples” configuration parameters when running dannce-predict (see the github wiki for more details).
c.	If you are asking how to label only specific cameras, I have not come across a use case for this – but if you wanted to, say, drop “Camera4” from all training and prediction, you could just modify the `label3d_dannce.mat` file to drop “Camera4” from “camnames” and also drop the 4th entry from “params”,”labelData”, and “sync”.
2)	The predictions have only 1000 entries because for the demo we set “max_num_samples” to 1000 – you can see this inside the configs/dannce_mouse_config.yaml file. Because “start_sample” is set to 0 (the default), then these predictions come from the first 1000 samples (i.e., frames). You can also always check which exact frames are contained in a prediction .mat file by examining the “sampleID” variable. The units of “sampleID” can be a bit flexible, so you shouldn’t assume that it is always the frame index, but you can always cross reference this “sampleID” with the “sync.data_sampleID” inside the `label3d_dannce.mat` file to find out which entries in “sync.data_frame” were used for prediction.

Please let me know if you have any other questions.
