### ISSUE TITLE
Response to Issue #87: Camera Calibration with MATLAB Camera Calibrator App

### ISSUE THREAD

**Issue by verpeutlab** [spoonsso/dannce#89]
Thank you for your response! (I am referencing the response I received in Issue #87  )I have the intrinsic matrix, radial distortion, and tangential distortion of the cameras. However, there are different values for the rotation matrix and translation vector for each checkerboard image that was imported into the MATLAB Camera Calibration App. Additionally, each value has different uncertainties, which are absent when these parameters are generated from the calibration script provided by DANNCE.
How should I use the rotation matrix and translation vector values generated by the MATLAB Camera Calibration App to determine the Radial Distortion and the Tangential Distortion for each camera using the script convertCalibration.m provided in DANNCE? Or, is there another way for me to finish calibrating if I used the MATLAB Camera Calibration App? Thank you!

_Originally posted by @verpeutlab in https://github.com/spoonsso/dannce/issues/87#issuecomment-1003894997_

**Comment by diegoaldarondo** [comment]
I think you're slightly confused about what we're talking about with respect to intrinsic and extrinsic calibration. 

Briefly, intrinsic calibration involves the estimation of camera parameters that are "intrinsic" to the camera. In practice, these will include the intrinsic matrix (containing the principal point and focal length), and the radial and tangential distortion coefficients (which describe distortion from the lens and sensor placement). The calibrator app is a convenient way to perform intrinsic calibration.

The rotation matrix and translation vectors you eventually will need for dannce are extrinsic parameters because they are extrinsic to the camera and define its position and orientation in a chosen coordinate frame. You will need the intrinsic parameters of all cameras to estimate their extrinsic parameters. The rotation matrices and translation vectors you get from the app are not relevant because they describe the position and orientation of the camera relative to the coordinate frames defined by the checkerboard in each of the calibration images, which are most likely not useful. 

There are many ways to do this, but one way is to perform extrinsic calibration by imaging a single checkerboard in the field of view all cameras simultaneously to estimate the position and orientation of each camera in a single convenient reference frame (The board usually lies flat on the ground, with the origin in a convenient location in the experiment). We do not have a public script to do this using intrinsics from the calibrator app, but the logic is similar to https://github.com/spoonsso/dannce/blob/cefd782aee1fce2044c7cef6237dfc207034fc68/calibration/acquire_calibration_3cam_mouse_clean.m#L204.

**Comment by spoonsso** [comment]
@verpeutlab I accidentally posted my reply (https://github.com/spoonsso/dannce/issues/87#issuecomment-1006914961) to #87 yesterday.

**Comment by yuan0821** [comment]
Sorry! I also confused the mean of extrinsic calibration. After performed calibration by Matlab app of Camera Calibrator, the results are as below:
![image](https://user-images.githubusercontent.com/50692530/151133642-57d24e28-05ae-4f5a-a4d6-f599641466fe.png)

1. The only useful information is: Intrinsic Matrix (including principle points and focal length) and radial/tangential distortion coefficients, for each camera?
2. The rotation matrix and translation vector generated are not useful?
3. If we want to get the extrinsic calibration, we should use a checkboard again, but put it in the field that all cameras can capture. Then what are the next steps? should calculate the rotation matrix and translation vector?

Thank you very much!!!
