### ISSUE TITLE
extrinsic calibration

### ISSUE THREAD

**Issue by yuan0821** [spoonsso/dannce#95]
Sorry! I put the question as a new issue here.
I also confused the mean of extrinsic calibration. After performed calibration by Matlab app of Camera Calibrator, the results are as below:
![image](https://user-images.githubusercontent.com/50692530/151133642-57d24e28-05ae-4f5a-a4d6-f599641466fe.png)

1. The only useful information is: Intrinsic Matrix (including principle points and focal length) and radial/tangential distortion coefficients, for each camera?
2. The rotation matrix and translation vector generated are not useful?
3. If we want to get the extrinsic calibration, we should use a checkboard again, but put it in the field that all cameras can capture. Then what are the next steps? should calculate the rotation matrix and translation vector?

Thank you very much!!!

_Originally posted by @yuan0821 in https://github.com/spoonsso/dannce/issues/89#issuecomment-1022003999_

**Comment by spoonsso** [comment]
Sorry, I do not normally use the camera calibrator app, but it looks like you could use it to do the multi-camera extrinsics as well. You would need to first save the Intrinsic Matrix and the distortion parameters you have here. Then, yes, put the checkerboard somewhere so that all cameras can see it. So each camera will get a view of the checkerboard in the exact same position. Save an image for each camera.

Once you have these images, you then want to calculate each camera's rotation and translation relative to the checkerboard, making sure the detected checkerboard from each camera view has all of the checkerboard points detected in the same order (so the same exact point can be called (0,0,0) in world coordinates. 

You might be able to use the camera calibrator app for this. In Optimization Options, you can put in values for the Intrinsic matrix and distortion coefficients. These would be the camera-specific parameters you found the first time you used the app. Then you could try to run the calibration to estimate a new rotation and translation for that camera.

An alternative is to save the detected checkerboard points and run them through estimateWorldCameraPose (https://www.mathworks.com/help/vision/ref/estimateworldcamerapose.html) followed by CameraPoseToExtrinsics (https://www.mathworks.com/help/vision/ref/cameraposetoextrinsics.html) to convert to rotation/translation.

**Comment by yuan0821** [comment]
Hi Tim,
I would like to ask if the alternative way (you mentioned above) still needs the same checkboard image for each camera before running estimateWorldCameraPose and CameraPoseToExtrinsics. I think if we want to get the rotation and translation across multiple camera relative to the checkboard, we need to use the image in the same position to calculate the extrinsic parameters. 

Another issue is our 3 cameras cannot capture a good full-view checkboard image at the same time because one of them is placed on the opposite of the others. Please kindly suggest if there is any method of calculating extrinsic parameters when the pattern can't be captured across all cameras.  Thank you so much!

![C1_177](https://user-images.githubusercontent.com/50692530/187415057-dd32ce3a-b74c-4a4f-ae37-e37d3fba6967.jpg)
![C2_177](https://user-images.githubusercontent.com/50692530/187414908-1c7ba555-6df8-4335-a1cb-fc49769ac01c.jpg)
![C3_177](https://user-images.githubusercontent.com/50692530/187414919-53e7b18a-8c4f-4fa3-b4b5-95e56ab29d6d.jpg)
